### PR TITLE
build: fix iOS/macOS C-linkage on HCWebSocketOptions; Android compileSdk 34; Linux WSC dl/pthread; UWP ARM64; GDK asio

### PR DESCRIPTION
**Pull request by v-patrickpe**
> Resubmitted from a branch in microsoft/libHttpClient (was [#985](https://github.com/microsoft/libHttpClient/pull/985) from a fork) so ADO CI ([libHttpClient.CI.yml](https://dev.azure.com/microsoft/Xbox/_build)) can auto-trigger. Same commits (`8c4efc0` + `2817f2e`); #985 will be closed in favor of this PR.

## Summary

Fixes 4 build regressions and 1 latent GDK build hazard surfaced by **PlayFab.SDKs.All TestDrop build [148660743](https://dev.azure.com/microsoft/Xbox/_build/results?buildId=148660743&view=results)**. TestDrop runs with `checkoutSubmodulesAsLatestCommit: true`, so it builds libHttpClient main HEAD against PlayFab.SDKs.All's iOS/macOS/Linux/GDK toolchains — exposing platform regressions that this repo's MSVC-only PR CI does not catch.

## Why these weren't caught upstream
libHttpClient `libHttpClient.CI.yml` builds primarily on MSVC/Windows. clang `-Wreturn-type-c-linkage` (Xcode iOS/macOS) and the Linux `WebSocketCompressionTests` link (`-ldl -lpthread`) never gated PR #965. Captured as follow-up: **AB#62563305**.

### `8c4efc0` — Android compileSdk 34 + UWP ARM64 warning + Linux WSC dl libs
- `Build/libHttpClient.Android/build.gradle` — compileSdk → 34 — **AB#62563300**
- `Build/libHttpClient.Linux/CMakeLists.txt` — add `dl pthread` to WSC test link — **AB#61359145**
- `Samples/UWP-Http/Http.vcxproj` — ARM64 -W4/-Werror suppression — **AB#62563301**

### `2817f2e` — iOS/macOS extern C++ wrap; GDK asio serial-port disable
- `Include/httpClient/httpClient.h` (line 1046) — wrap `DEFINE_ENUM_FLAG_OPERATORS(HCWebSocketOptions)` in `extern ""C++"" { }` so the C++ operator overloads aren't inside the file-wide `extern ""C""` block (clang `-Wreturn-type-c-linkage -Werror` reject) — **AB#62563298**
- `Build/libHttpClient.GDK.props` — add `ASIO_DISABLE_SERIAL_PORT` to PreprocessorDefinitions; GDK `NOSERIALCOMM` removes `DCB` which breaks asio's `win_iocp_serial_port_service` (pulled in via websocketpp) — **AB#62563299**

## Repro (iOS/macOS)
```
httpClient.h:1046:1: error: 'operator|=' has C-linkage specified, but
  returns user-defined type 'HCWebSocketOptions &' which is incompatible
  with C [-Werror,-Wreturn-type-c-linkage]
```
Introduced by #965 (`b19d186`) placing the macro inside the file-wide `extern ""C"" {` (opened L24, closed L1496). MSVC and gcc tolerate it; clang `-Werror` does not. Minimal fix preserves C linkage for the entire public API surface and only flips to `C++` for the 1-line macro expansion.

## Risk
- `extern ""C++""` around a macro is standard C++; supported by MSVC/clang/gcc. No ABI impact — operator overloads were never callable from C.
- `ASIO_DISABLE_SERIAL_PORT` only removes a transport we never use. No runtime behavior change. asio config knob at `External/asio/asio/include/asio/detail/config.hpp:1066-1080`.

## Validation
Pre-merge validated via PFSDKAll TestDrop build [148684233](https://dev.azure.com/microsoft/Xbox/_build/results?buildId=148684233) (with this tip pinned as the libHttpClient submodule). All 4 in-scope fixes confirmed:
- iOS/macOS operator-linkage — Xcode jobs green
- Linux WSC `dl pthread` — libHttpClient static builds clean
- GDK `ASIO_DISABLE_SERIAL_PORT` — applies; full GDK still blocked separately on NuGet feed gap
- Android compileSdk 34 / UWP ARM64 — assemble paths reached

## Related ADO work items
- **AB#62563298** — iOS/macOS HCWebSocketOptions C-linkage
- **AB#62563299** — GDK asio NOSERIALCOMM/DCB
- **AB#62563300** — Android compileSdk 34
- **AB#62563301** — UWP ARM64 warning
- **AB#61359145** — Linux WSC `dl/pthread` (Raul)
- **AB#62563305** — Follow-up: libHttpClient CI gate-job gap

### CODE REVIEW

File: Build/libHttpClient.GDK.props [hunk 1]
```diff
@@ -106,7 +106,12 @@
       <TreatWarningAsError>true</TreatWarningAsError>
       <SupportJustMyCode>false</SupportJustMyCode>
       <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
-      <PreprocessorDefinitions>__WRL_NO_DEFAULT_LIB__;_LIB;$(libHttpClientDefine);%(PreprocessorDefinitions)</PreprocessorDefinitions>
+      <!--
+        ASIO_DISABLE_SERIAL_PORT: GDK builds compile with NOSERIALCOMM (no DCB),
+        which breaks asio's win_iocp_serial_port_service. asio is pulled in via
+        websocketpp; we don't use its serial-port transport, so disable it.
+      -->
+      <PreprocessorDefinitions>__WRL_NO_DEFAULT_LIB__;_LIB;ASIO_DISABLE_SERIAL_PORT;$(libHttpClientDefine);%(PreprocessorDefinitions)</PreprocessorDefinitions>
```
Comment (rgomez391) [inline Build/libHttpClient.GDK.props:114]: I wonder if this change is required or not, I imagine affects GDK, but shouldn't affect Android right?

File: Samples/UWP-Http/Http.vcxproj [hunk 2]
```diff
@@ -9,6 +9,7 @@
   <ItemDefinitionGroup>
     <ClCompile>
       <PreprocessorDefinitions>_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING;%(PreprocessorDefinitions)</PreprocessorDefinitions>
+      <TreatWarningAsError Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">false</TreatWarningAsError>
```
Comment (rgomez391) [inline Samples/UWP-Http/Http.vcxproj:12]: Same comment with this one, probably not affecting Android, please confirm if that's the case.

Comment (v-patrickpe) [reply Samples/UWP-Http/Http.vcxproj:12]: Confirmed, same as the GDK.props change, no Android impact.

Samples/UWP-Http/Http.vcxproj is UWP-only (Win32 ARM64 configuration). Android never touches this project file.

The warning suppress unblocks the UWP ARM64 Release leg that was failing in the same TestDrop.

Same offer: can split if you'd rather keep this PR tightly scoped.

File: Build/libHttpClient.GDK.props (hunk 1 above)
Comment (v-patrickpe) [reply Build/libHttpClient.GDK.props:114]: Confirmed, no Android impact.

Build/libHttpClient.GDK.props is only included by .vcxproj projects that select GDK targets. The Android build path goes through Build/CMake/* via gradle and never evaluates this props file.

The ASIO_DISABLE_SERIAL_PORT flag fixes a GDK Release break that surfaced in the same TestDrop run that exposed the Android issue, so I bundled the two.

Can split into a follow-up PR if you'd prefer keeping #987 strictly Android-scoped.

**Review by rgomez391 — APPROVED** [review]
